services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banglz_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/vendor
    networks:
      - banglz
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "composer install && php artisan key:generate && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: banglz_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: banglz
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: banglz_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - banglz
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: banglz_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - banglz
    depends_on:
      - db

networks:
  banglz:
    driver: bridge

volumes:
  dbdata:
    driver: local
